spring:
  application:
  name: openapi-platform-gateway
  cloud:
    gateway:
      routes:
        - id: api
          uri: http://localhost:8765/api/**
          predicates:
            - Path=/api/**
        - id: web
          uri: http://localhost:8101/api/**
          predicates:
            - Path=/web/**


server:
  address: 0.0.0.0
  port: 8890

dubbo:
  application:
    name: openapi-platform-gateway
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848


